DROP TABLE IF EXISTS ACCOMMODATION CASCADE;
CREATE TABLE ACCOMMODATION (
    ACMD_NO BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(1000) NOT NULL,
    LATITUDE DOUBLE,
    LONGITUDE DOUBLE,
    TYPE VARCHAR(255) NOT NULL,
    IS_FREE_PARKING BOOLEAN,
    PARKING_TYPE VARCHAR(255),
    LOCATION_GUIDE_TEXT VARCHAR(255)
);

DROP TABLE IF EXISTS IMAGE CASCADE;
CREATE TABLE IMAGE (
    IMAGE_NO BIGINT AUTO_INCREMENT PRIMARY KEY,
    IMAGE_TYPE VARCHAR(255) NOT NULL,
    PATH VARCHAR(255) NOT NULL,
    ACMD_NO BIGINT NOT NULL
);

DROP TABLE IF EXISTS AMENITY CASCADE;
CREATE TABLE AMENITY (
    AMENITY_NO BIGINT AUTO_INCREMENT PRIMARY KEY,
    DESCRIPTION VARCHAR(255),
    NAME VARCHAR(255) NOT NULL UNIQUE
);

DROP TABLE IF EXISTS ACCOMMODATION_AMENITY CASCADE;
CREATE TABLE ACCOMMODATION_AMENITY (
    ACMD_AMENITY_NO BIGINT AUTO_INCREMENT PRIMARY KEY,
    ACMD_NO BIGINT NOT NULL,
    AMENITY_NO BIGINT NOT NULL,
    IS_AVAILABLE BOOLEAN NOT NULL
);